apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-metrics
  namespace: argocd
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-metrics
  endpoints:
    - port: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-service-metrics
  namespace: demo-app
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: frontend
  namespaceSelector:
    matchNames:
      - demo-app
  endpoints:
    - port: http
      scheme: http
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: adservice-metrics
  namespace: demo-app
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: adservice
  namespaceSelector:
    matchNames:
      - demo-app
  endpoints:
    - port: metrics
      scheme: http
