apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 72.3.1
      chart: kube-prometheus-stack
      helm:
        valueFiles:
          - $values/prometheus/config/values.yaml
    - repoURL: "https://github.com/agh-cs-imbeciles/argo-otel.git"
      ref: values
      targetRevision: main
    - repoURL: "https://github.com/agh-cs-imbeciles/argo-otel.git"
      path: "prometheus/manifest"
      targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
