apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana
      targetRevision: 9.2.1
      helm:
        releaseName: grafana
        values: |
          adminUser: admin
          adminPassword: admin
          persistence:
            enabled: false
          service:
            type: ClusterIP
          ingress:
            enabled: false
          defaultDashboardsEnabled: true
          sidecar:
            dashboards:
              enabled: true
              label: grafana_dashboard
          datasources:
            datasources.yaml:
              apiVersion: 1
              datasources:
                - name: Prometheus
                  type: prometheus
                  access: proxy
                  url: http://prometheus-operated.monitoring.svc.cluster.local
                  isDefault: true
                - name: Tempo
                  type: tempo
                  access: proxy
                  url: http://tempo.monitoring.svc.cluster.local
    - repoURL: "https://github.com/agh-cs-imbeciles/argo-otel.git"
      path: "grafana/manifest"
      targetRevision: promo
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
